/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 15 17:52:53 GMT 2021
 */

package com.varma.main.entity;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.Date;

import org.junit.Test;

public class ErrorDetailsTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ErrorDetails errorDetails0 = new ErrorDetails();
      String string0 = errorDetails0.getErrorDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ErrorDetails errorDetails0 = new ErrorDetails(0, "", (Date) null);
      errorDetails0.getErrorDescription();
      assertEquals(0, errorDetails0.getErrorCode());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Date Date0 = new Date(1, 1, 1);
      ErrorDetails errorDetails0 = new ErrorDetails(1, (String) null, Date0);
      int int0 = errorDetails0.getErrorCode();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Date Date0 = new Date((-157));
      ErrorDetails errorDetails0 = new ErrorDetails((-157), "errorDescription=", Date0);
      int int0 = errorDetails0.getErrorCode();
      assertEquals((-157), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ErrorDetails errorDetails0 = new ErrorDetails();
      Date Date0 = new Date(249L);
      errorDetails0.setCreated(Date0);
      Date date0 = errorDetails0.getCreated();
      assertEquals("Thu Jan 01 00:00:00 GMT 1970", date0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Date Date0 = new Date(136, 136, 136, 136, 136);
      ErrorDetails errorDetails0 = new ErrorDetails(136, "G>_*BRF", Date0);
      String string0 = errorDetails0.toString();
      assertEquals("ErrorDetails [errorCode=136, errorDescription=G>_*BRF, created=Wed Sep 18 18:16:00 GMT 2047]", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ErrorDetails errorDetails0 = new ErrorDetails();
      String string0 = errorDetails0.toString();
      assertEquals("ErrorDetails [errorCode=0, ]", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ErrorDetails errorDetails0 = new ErrorDetails();
      int int0 = errorDetails0.getErrorCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Date Date0 = new Date(136, 136, 136, 136, 136);
      ErrorDetails errorDetails0 = new ErrorDetails(136, "G>_*BRF", Date0);
      errorDetails0.setErrorDescription("G>_*BRF");
      assertEquals(136, errorDetails0.getErrorCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Date Date0 = new Date(136, 136, 136, 136, 136);
      ErrorDetails errorDetails0 = new ErrorDetails(136, "G>_*BRF", Date0);
      errorDetails0.setErrorCode(136);
      assertEquals(136, errorDetails0.getErrorCode());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Date Date0 = new Date(136, 136, 136, 136, 136);
      ErrorDetails errorDetails0 = new ErrorDetails(136, "G>_*BRF", Date0);
      errorDetails0.getErrorDescription();
      assertEquals(136, errorDetails0.getErrorCode());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ErrorDetails errorDetails0 = new ErrorDetails();
      Date date0 = errorDetails0.getCreated();
      assertNull(date0);
  }
}
