/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 14 21:00:01 GMT 2021
 */

package com.varma.main.entity;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.util.Date;

import org.junit.Test;

public class ProductTest {
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Product product0 = new Product();
      product0.setPrice((-1.0));
      product0.hashCode();
      assertEquals((-1.0), product0.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Product product0 = new Product();
      product0.setId("");
      String string0 = product0.getCategory();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Product product0 = new Product();
      Date date0 = new Date();
      product0.setUpdated(date0);
      Date date1 = product0.getUpdated();
      assertSame(date1, date0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Date Date0 = new Date();
      Product product0 = new Product("sfDz:EV)Ph]", "sfDz:EV)Ph]", "sfDz:EV)Ph]", 1.0, Date0, Date0);
      double double0 = product0.getPrice();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Date Date0 = new Date();
      Product product0 = new Product("@0g#H", "y mWI-dF@Qugp{Z~", "@0g#H", 0.0, Date0, Date0);
      String string0 = product0.getId();
      assertEquals("y mWI-dF@Qugp{Z~", product0.getDescription());
      assertNotNull(string0);
      assertEquals(0.0, product0.getPrice(), 0.01);
      assertEquals("@0g#H", product0.getCategory());
      assertEquals("@0g#H", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Product product0 = new Product();
      product0.setId("");
      String string0 = product0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Product product0 = new Product();
      String string0 = product0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Date Date0 = new Date(1561, 1561, 1561);
      Product product0 = new Product("", "", "", (-3415.64), Date0, Date0);
      String string0 = product0.getDescription();
      assertNotNull(string0);
      assertEquals((-3415.64), product0.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Date Date0 = new Date(1561, 1561, 1561);
      Product product0 = new Product("", "", "", (-3415.64), Date0, Date0);
      String string0 = product0.getCategory();
      assertEquals((-3415.64), product0.getPrice(), 0.01);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Product product0 = new Product();
      Product product1 = new Product();
      boolean boolean0 = product0.equals(product1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Product product0 = new Product();
      Date Date0 = new Date();
      Product product1 = new Product();
      assertTrue(product1.equals((Object)product0));
      
      product0.setCreated(Date0);
      boolean boolean0 = product1.equals(product0);
      assertFalse(product1.equals((Object)product0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Product product0 = new Product();
      Date Date0 = new Date((-4566689604572282880L));
      Product product1 = new Product("created=", (String) null, "cF4P9m", 0.0, Date0, Date0);
      boolean boolean0 = product0.equals(product1);
      assertFalse(boolean0);
      assertEquals("cF4P9m", product1.getCategory());
      assertEquals(0.0, product1.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Product product0 = new Product();
      Product product1 = new Product("", (String) null, (String) null, 0.0, (Date) null, (Date) null);
      boolean boolean0 = product0.equals(product1);
      assertFalse(product1.equals((Object)product0));
      assertFalse(boolean0);
      assertEquals(0.0, product1.getPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Product product0 = new Product();
      boolean boolean0 = product0.equals(product0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Product product0 = new Product();
      boolean boolean0 = product0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Date Date0 = new Date();
      Product product0 = new Product("?AJU_S#vG[53uz,", "y mWI-dF@Qugp{Z~", "?AJU_S#vG[53uz,", 0.0, Date0, Date0);
      product0.hashCode();
      assertEquals("?AJU_S#vG[53uz,", product0.getCategory());
      assertEquals("y mWI-dF@Qugp{Z~", product0.getDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Product product0 = new Product();
      String string0 = product0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Product product0 = new Product();
      product0.setCategory("");
      assertNull(product0.getId());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Product product0 = new Product();
      double double0 = product0.getPrice();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Product product0 = new Product();
      Date date0 = product0.getUpdated();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Product product0 = new Product();
      product0.setId("");
      Product product1 = new Product("", (String) null, (String) null, 0.0, (Date) null, (Date) null);
      boolean boolean0 = product0.equals(product1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Date Date0 = new Date();
      Product product0 = new Product("?AJU_S#vG[53uz,", "y mWI-dF@Qugp{Z~", "?AJU_S#vG[53uz,", 0.0, Date0, Date0);
      Date date0 = product0.getCreated();
      assertNotNull(date0);
      assertEquals(0.0, product0.getPrice(), 0.01);
      assertEquals("y mWI-dF@Qugp{Z~", product0.getDescription());
      assertEquals("?AJU_S#vG[53uz,", product0.getCategory());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Date Date0 = new Date();
      Product product0 = new Product("?AJU_S#vG[53uz,", "y mWI-dF@Qugp{Z~", "?AJU_S#vG[53uz,", 0.0, Date0, Date0);
      String string0 = product0.getCategory();
      assertNotNull(string0);
      assertEquals(0.0, product0.getPrice(), 0.01);
      assertEquals("y mWI-dF@Qugp{Z~", product0.getDescription());
      assertEquals("?AJU_S#vG[53uz,", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Date Date0 = new Date();
      Product product0 = new Product("?AJU_S#vG[53uz,", "y mWI-dF@Qugp{Z~", "?AJU_S#vG[53uz,", 0.0, Date0, Date0);
      String string0 = product0.getDescription();
      assertEquals("?AJU_S#vG[53uz,", product0.getCategory());
      assertNotNull(string0);
      assertEquals(0.0, product0.getPrice(), 0.01);
      assertEquals("y mWI-dF@Qugp{Z~", string0);
  }
}
