/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 14 21:02:20 GMT 2021
 */

package com.varma.main.service;

import static org.junit.jupiter.api.Assertions.fail;

import java.util.Date;
import java.util.List;

import org.junit.Test;

import com.varma.main.entity.Cart;
import com.varma.main.entity.Product;

public class CartServiceTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CartService cartService0 = new CartService();
      Cart cart0 = new Cart();
      // Undeclared exception!
      try { 
        cartService0.addCart(cart0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/CartRepository
         //
         verifyException("com.varma.main.service.CartService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CartService cartService0 = new CartService();
      // Undeclared exception!
      try { 
        cartService0.getAllCarts();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/CartRepository
         //
         verifyException("com.varma.main.service.CartService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CartService cartService0 = new CartService();
      // Undeclared exception!
      try { 
        cartService0.deleteCart(":ia^wTnRGsuQUz)p");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/CartRepository
         //
         verifyException("com.varma.main.service.CartService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CartService cartService0 = new CartService();
      Date Date0 = new Date(0, (-1), (-1), 0, 0);
      Cart cart0 = new Cart("\"B0df`pa%Bf(4PSk6", "\"B0df`pa%Bf(4PSk6", "\"B0df`pa%Bf(4PSk6", Date0, Date0, (List<Product>) null);
      // Undeclared exception!
      try { 
        cartService0.updateCart(cart0, "created=");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/CartRepository
         //
         verifyException("com.varma.main.service.CartService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CartService cartService0 = new CartService();
      // Undeclared exception!
      try { 
        cartService0.getCart((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/CartRepository
         //
         verifyException("com.varma.main.service.CartService", e);
      }
  }
  
  private void verifyException(String message, Error e) {
	// TODO Auto-generated method stub
	fail(message, e);
  }
  
  private void verifyException(String message, Exception e) {
	// TODO Auto-generated method stub
		fail(message, e);
  }

  
}
