/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 15 17:55:23 GMT 2021
 */

package com.varma.main.service;

import static org.junit.jupiter.api.Assertions.fail;

import org.junit.Test;

import com.varma.main.entity.ErrorDetails;

public class ErrorResponseServiceTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = (-399);
      int int1 = 3604;
      String string0 = null;
      // Undeclared exception!
      try { 
        errorResponseService0.getInternalServerErrorRespone(3604, (String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 1;
      String string0 = "";
      // Undeclared exception!
      try { 
        errorResponseService0.getBadRequestErrorRespone(1035, "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      ErrorDetails errorDetails0 = new ErrorDetails();
      errorResponseService0.errorDetails = errorDetails0;
      int int0 = (-1298);
      errorDetails0.toString();
      String string0 = "pw\"";
      errorDetails0.setErrorDescription("pw\"");
      errorDetails0.setErrorDescription("pw\"");
      // Undeclared exception!
      try { 
        errorResponseService0.getFoundErrorRespone((-1298), ", ");
        fail("Expecting exception: NoSuchFieldError");
      
      } catch(NoSuchFieldError e) {
         //
         // FOUND
         //
         verifyException("com.varma.main.service.ErrorResponseService", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      // Undeclared exception!
      try { 
        errorResponseService0.getNotFoundErrorRespone((-828), ">HLUkkT&v89nVF|,");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = (-830);
      ErrorDetails errorDetails0 = new ErrorDetails();
      errorResponseService0.errorDetails = errorDetails0;
      String string0 = "";
      // Undeclared exception!
      try { 
        errorResponseService0.getBadRequestErrorRespone((-830), "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 0;
      String string0 = "]";
      // Undeclared exception!
      try { 
        errorResponseService0.getBadRequestErrorRespone(0, "]");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 0;
      String string0 = "";
      // Undeclared exception!
      try { 
        errorResponseService0.getInternalServerErrorRespone(0, "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 0;
      // Undeclared exception!
      try { 
        errorResponseService0.getNotFoundErrorRespone(0, "com.varma.main.service.ErrorResponseService");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 0;
      String string0 = "";
      // Undeclared exception!
      try { 
        errorResponseService0.getFoundErrorRespone(0, "");
        fail("Expecting exception: NoSuchFieldError");
      
      } catch(NoSuchFieldError e) {
         //
         // FOUND
         //
         verifyException("com.varma.main.service.ErrorResponseService", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      // Undeclared exception!
      try { 
        errorResponseService0.getInternalServerErrorRespone(0, (String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      ErrorDetails errorDetails0 = new ErrorDetails();
      errorResponseService0.errorDetails = errorDetails0;
      errorResponseService0.errorDetails = errorDetails0;
      errorDetails0.setErrorDescription("/`Mvd\u0003");
      String string0 = null;
      // Undeclared exception!
      try { 
        errorResponseService0.getNotFoundErrorRespone(0, (String) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 87;
      ErrorDetails errorDetails0 = new ErrorDetails();
      errorResponseService0.errorDetails = errorDetails0;
      // Undeclared exception!
      try { 
        errorResponseService0.getBadRequestErrorRespone(87, "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ErrorResponseService errorResponseService0 = new ErrorResponseService();
      int int0 = 0;
      ErrorDetails errorDetails0 = new ErrorDetails();
      errorResponseService0.errorDetails = errorDetails0;
      // Undeclared exception!
      try { 
        errorResponseService0.getBadRequestErrorRespone(0, "|//lI");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
         //
         verifyException("javax.ws.rs.ext.RuntimeDelegate", e);
      }
  }
  
  private void verifyException(String message, Error e) {
	// TODO Auto-generated method stub
	fail(message, e);
  }
  
  private void verifyException(String message, Exception e) {
	// TODO Auto-generated method stub
		fail(message, e);
  }

}
