/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 14 21:03:51 GMT 2021
 */

package com.varma.main.service;

import static org.junit.jupiter.api.Assertions.fail;

import org.junit.Test;

import com.varma.main.entity.CartProduct;
import com.varma.main.entity.Product;

public class ProductServiceTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.deleteProductFromCart("~6", "Product [");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }


@Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.deleteProduct("FI0EMeH3'hw");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/ProductRepository
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.getAllProducts();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/ProductRepository
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CartProduct cartProduct0 = new CartProduct();
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.addProductsToCart(cartProduct0, "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/ProductRepository
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Product product0 = new Product();
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.updateProduct(product0, "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/ProductRepository
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.getAllProductsFromCart("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ProductService productService0 = new ProductService();
      Product product0 = new Product();
      // Undeclared exception!
      try { 
        productService0.addProduct(product0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/ProductRepository
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.getProduct("e}{$pdz");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/varma/main/repository/ProductRepository
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ProductService productService0 = new ProductService();
      // Undeclared exception!
      try { 
        productService0.getProductFromCart("", "cb$|ZorZ/sEWm");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.varma.main.service.ProductService", e);
      }
  }
  
  private void verifyException(String message, Error e) {
	// TODO Auto-generated method stub
	fail(message, e);
  }
  
  private void verifyException(String message, Exception e) {
	// TODO Auto-generated method stub
		fail(message, e);
  }
  
}
