/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 15 17:56:12 GMT 2021
 */

package com.varma.main.controller;

import static org.junit.Assert.fail;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.Date;

import org.junit.Test;

import com.varma.main.entity.Cart;
public class CartControllerTest{

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CartController cartController0 = new CartController();
      Cart cart0 = new Cart();
      // Undeclared exception!
      try { 
        cartController0.addCart(cart0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CartController cartController0 = new CartController();
      Cart cart0 = new Cart();
      cart0.toString();
      // Undeclared exception!
      try { 
        cartController0.updateCart(cart0, "_$~TU[L");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CartController cartController0 = new CartController();
      String string0 = "";
      // Undeclared exception!
      try { 
        cartController0.getCart("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }



@Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CartController cartController0 = new CartController();
      cartController0.cartService = null;
      // Undeclared exception!
      try { 
        cartController0.getAllCarts();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CartController cartController0 = new CartController();
      String string0 = "hq$oUJO~uXeX3]eS";
      // Undeclared exception!
      try { 
        cartController0.deleteCart("hq$oUJO~uXeX3]eS");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CartController cartController0 = new CartController();
      // Undeclared exception!
      try { 
        cartController0.getCart("product=");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CartController cartController0 = new CartController();
      // Undeclared exception!
      try { 
        cartController0.getAllCarts();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CartController cartController0 = new CartController();
      Cart cart0 = new Cart();
      String string0 = null;
      Date Date0 = new Date();
      FormatStyle formatStyle0 = FormatStyle.SHORT;
      DateTimeFormatter dateTimeFormatter0 = DateTimeFormatter.ofLocalizedDate(formatStyle0);
      // Undeclared exception!
      try { 
        LocalDate.parse((CharSequence) null, dateTimeFormatter0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // text
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CartController cartController0 = new CartController();
      Cart cart0 = null;
      // Undeclared exception!
      try { 
        cartController0.addCart((Cart) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CartController cartController0 = new CartController();
      // Undeclared exception!
      try { 
        cartController0.getCart("0&2 0*SsVc>");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CartController cartController0 = new CartController();
      // Undeclared exception!
      try { 
        cartController0.deleteCart("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/util/StringUtils
         //
         verifyException("com.varma.main.controller.CartController", e);
      }
  }
  
  private void verifyException(String string, Error e) {
	// TODO Auto-generated method stub
	fail(string+e.getMessage());
  }
  
  private void verifyException(String string, Exception e) {
	// TODO Auto-generated method stub
	fail(string+e.getMessage());
  }
  
}
