/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 14 21:09:03 GMT 2021
 */

package com.varma.main;

import static org.junit.Assert.*;

import org.junit.jupiter.api.Test;

public class CartApiApplicationTest {

  @Test
  public void test0()  throws Throwable  {
      CartApiApplication cartApiApplication0 = new CartApiApplication();
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        CartApiApplication.main((String[]) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/boot/SpringApplication
         //
    	  fail("com.varma.main.CartApiApplication"+e.getMessage());
      }
  }
}
